import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export type PayslipPdfInput = {
  companyName?: string;
  employeeName: string;
  employeeEmail?: string;
  employeeNumber?: string | null;
  jobTitle?: string | null;
  department?: string | null;
  periodStart: string;
  periodEnd: string;
  payType: string;
  payRate: number;
  regularHours: number;
  overtimeHours: number;
  regularPay: number;
  overtimePay: number;
  grossPay: number;
  taxAmount: number;
  otherDeductions: number;
  sssEmployee?: number;
  philhealthEmployee?: number;
  pagibigEmployee?: number;
  netPay: number;
  calcNote?: string | null;
};

function money(n: number): string {
  return `PHP ${Number(n).toFixed(2)}`;
}

export async function buildPayslipPdf(
  input: PayslipPdfInput,
): Promise<Buffer> {
  const doc = await PDFDocument.create();
  const page = doc.addPage([612, 792]); // LETTER
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const fontBold = await doc.embedFont(StandardFonts.HelveticaBold);

  const left = 50;
  let y = 742;
  const lineGap = 16;

  const write = (
    text: string,
    opts?: { bold?: boolean; size?: number; color?: ReturnType<typeof rgb> },
  ) => {
    const size = opts?.size ?? 10;
    const used = opts?.bold ? fontBold : font;
    page.drawText(text, {
      x: left,
      y,
      size,
      font: used,
      color: opts?.color ?? rgb(0, 0, 0),
    });
    y -= lineGap;
  };

  const company = input.companyName ?? "Payroll Management";
  write(company, { bold: true, size: 18 });
  write("Payslip", { size: 12, color: rgb(0.3, 0.3, 0.3) });
  y -= 8;

  write(`Employee: ${input.employeeName}`);
  if (input.employeeNumber) write(`Employee #: ${input.employeeNumber}`);
  if (input.employeeEmail) write(`Email: ${input.employeeEmail}`);
  if (input.jobTitle) write(`Title: ${input.jobTitle}`);
  if (input.department) write(`Department: ${input.department}`);
  write(`Pay period: ${input.periodStart} to ${input.periodEnd}`);
  write(`Pay type: ${input.payType} · Rate: ${money(input.payRate)}`);
  y -= 8;

  write("Earnings", { bold: true, size: 11 });
  write(`Regular hours: ${Number(input.regularHours).toFixed(2)}`);
  write(`Overtime hours: ${Number(input.overtimeHours).toFixed(2)}`);
  write(`Regular pay: ${money(input.regularPay)}`);
  write(`Overtime pay: ${money(input.overtimePay)}`);
  write(`Gross pay: ${money(input.grossPay)}`);
  y -= 8;

  write("Deductions", { bold: true, size: 11 });
  write(`SSS (EE): ${money(input.sssEmployee ?? 0)}`);
  write(`PhilHealth (EE): ${money(input.philhealthEmployee ?? 0)}`);
  write(`Pag-IBIG (EE): ${money(input.pagibigEmployee ?? 0)}`);
  write(`BIR withholding: ${money(input.taxAmount)}`);
  if (input.otherDeductions > 0) {
    write(`Statutory subtotal: ${money(input.otherDeductions)}`);
  }
  y -= 8;

  write(`Net pay: ${money(input.netPay)}`, { bold: true, size: 12 });

  if (input.calcNote) {
    y -= 8;
    write(`Note: ${input.calcNote}`, { size: 9, color: rgb(0.4, 0.4, 0.4) });
  }

  y -= 24;
  write("Generated by Payroll Management. For employee records only.", {
    size: 8,
    color: rgb(0.55, 0.55, 0.55),
  });

  const bytes = await doc.save();
  return Buffer.from(bytes);
}
